routes/web.php
<?php

use App\Livewire\Coordinator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DealerController;
use App\Http\Controllers\EndUserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\RetailerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PriceMonitoringController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function() {
    return redirect()->route('app.dashboard');
});

Auth::routes();

Route::group(['prefix' => 'app', 'as' => 'app.', 'middleware' => 'auth'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('settings', SettingController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('dealers', DealerController::class);
    Route::resource('retailers', RetailerController::class);
    Route::resource('price-monitoring', PriceMonitoringController::class);
    Route::resource('end-users', EndUserController::class);
});

app/Models/EndUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EndUser extends Model
{
    use HasFactory;
    protected $fillable = [
        'business_name',
        'business_address',
        'owner_name',
        'contact',
        'product_id',
        'state_id',
        'lga_id',
        'consumption',
        'consumption_monthly',
        'consumption_annual',
        'percentage_bua',
        'percentage_others'
    ];

    public function state()  {
        return $this->belongsTo(State::class);
    }

    public function lga()  {
        return $this->belongsTo(Lga::class);
    }

    public function product()  {
        return $this->belongsTo(Product::class);
    }
}

app/Http/Controllers/EndUserController.php
<?php

namespace App\Http\Controllers;

use App\Models\State;
use App\Models\EndUser;
use App\Models\Product;
use App\Models\Retailer;
use Illuminate\Http\Request;

class EndUserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $lgaconsumptions = [];
        $usersconsumptions = [];
        $endUsers = EndUser::with('product')->get();
        $percent_bua = $endUsers->where('product.product', "BUA CEMENT")->count();
        $percent_others = $endUsers->where('product.product', '!=', "BUA CEMENT")->count();
        // dd($percent_others);
        $users = EndUser::all();
        foreach ($users as $user) {
            $lgaConsumption = EndUser::where('lga_id', $user->lga->id)->sum('consumption');
            $userConsumption = EndUser::where('business_name', $user->business_name)->sum('consumption');
            $topuser = EndUser::where('business_name', $user->business_name)->sum('consumption');
            $lgaconsumptions[] = [
                'name' => $user->lga->name,
                'y' => $lgaConsumption ?: 0,
                'drilldown' => $user->lga->name,
            ];
            $usersconsumptions[] = [
                'name' => $user->business_name,
                'y' => $userConsumption ?: 0,
                'drilldown' => $user->business_name,
            ];

        }
        return view('end-users.index', compact('percent_bua', 'percent_others', 'lgaconsumptions', 'usersconsumptions'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $products = Product::all();
        $states = State::all();
        return view('end-users.create', compact('products', 'states'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $endUser = EndUser::create($request->all());
        return redirect()->route('app.end-users.index')->with('success', 'End User created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(EndUser $endUser)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(EndUser $endUser)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, EndUser $endUser)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(EndUser $endUser)
    {
        $endUser->delete();
        return redirect()->route('app.end-users.index')->with('success', 'End User deleted successfully');
    }
}

app/Livewire/EndUsers.php
<?php

namespace App\Livewire;

use App\Models\EndUser;
use Livewire\Component;

class EndUsers extends Base
{
    public $sortBy = 'business_name';
    public function render()
    {
        if ($this->search) {
            $endusers = EndUser::query()
                ->where('business_name', 'like', '%' . $this->search . '%')
                ->paginate(10);

            return view(
                'livewire.end-users',
                ['endusers' => $endusers]
            );
        } else {
            $endusers = EndUser::orderBy($this->sortBy, $this->sortDirection)
            ->paginate(10);
            return view(
                'livewire.end-users',
                ['endusers' => $endusers]
            );
        }
    }
}

resources/views/end-users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Toolbar-->
        <div class="toolbar" id="kt_toolbar">
            <!--begin::Container-->
            <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
                <!--begin::Page title-->
                <div data-kt-swapper="true" data-kt-swapper-mode="prepend"
                    data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}"
                    class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
                    <!--begin::Title-->
                    <h1 class="d-flex text-dark fw-bolder fs-3 align-items-center my-1">Retailers Records</h1>
                    <!--end::Title-->
                    <!--begin::Separator-->
                    <span class="h-20px border-gray-300 border-start mx-4"></span>
                    <!--end::Separator-->
                    <!--begin::Breadcrumb-->
                    <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
                        <!--begin::Item-->
                        <li class="breadcrumb-item text-muted">
                            <a href="{{ route('app.dashboard') }}" class="text-muted text-hover-primary">Home</a>
                        </li>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <li class="breadcrumb-item text-muted"><a href="{{ route('app.retailers.index') }}"
                                class="text-muted text-hover-primary">End Users Record</a></li>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <li class="breadcrumb-item text-dark">New Record</li>
                        <!--end::Item-->
                    </ul>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Page title-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Toolbar-->
        <!--begin::Post-->
        <div class="post d-flex flex-column-fluid" id="kt_post">
            <!--begin::Container-->
            <div id="kt_content_container" class="container-xxl">
                <!--begin::Card-->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">New End User Record</h3>
                    </div>
                    <!-- /.card-header -->
                    <form action="{{ route('app.end-users.store') }}" method="POST">
                        @csrf
                        <!-- form start -->
                        <div class="card-body">
                            <div class="form-group">
                                <label>Business Name</label>
                                <input type="text" name="business_name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Business Address</label>
                                <input type="text" name="business_address" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Name of Owner</label>
                                <input type="text" name="owner_name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Contact No</label>
                                <input type="text" name="contact" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Product</label>
                                <select name="product_id" id="" class="form-control">
                                   @foreach ($products as $product)
                                        <option value="{{$product->id}}">{{$product->product}}</option>
                                   @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>State</label>
                                <select name="state_id" id="state" class="form-control">
                                    <option value="" selected>Select State</option>
                                    @foreach ($states as $state)
                                        <option value="{{ $state->id }}">{{ $state->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Lga</label>
                                <select name="lga_id" id="lga" class="form-control">

                                </select>
                            </div>
                            <div class="form-group">
                                <label>Daily Consumption</label>
                                <input type="number" name="consumption" id="daily_consumption" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Projected Monthly Consumption</label>
                                <input type="number" readonly name="consumption_monthly" id="monthly_consumption" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Projected Annually Consumption</label>
                                <input type="number" readonly name="consumption_annual" id="annual_consumption" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Percentage of BUA</label>
                                <input type="number" name="percentage_bua" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Percentage of Others</label>
                                <input type="number" name="percentage_others" class="form-control">
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Post-->
    </div>
    <script>
        var state = document.getElementById("state");
        var lga = document.getElementById("lga");
        var daily_consumption = document.getElementById("daily_consumption");
        var monthly_consumption = document.getElementById("monthly_consumption");
        var annual_consumption = document.getElementById("annual_consumption");
        let Url = '{{ url('/api/') }}';

        lga.length = 0;

        let defaultOption = document.createElement('option');
        defaultOption.text = 'Choose LGA';

        lga.add(defaultOption);
        lga.selectedIndex = 0;

        state.addEventListener("change", function() {
            // alert(state.value);

            fetch(Url + '/getLGA/' + state.value)
                .then((res) => res.json())
                .then((data) => {
                    console.log(data)
                    document.getElementById("lga").innerHTML = "";
                    let option;
                    data.forEach(element => {
                        option = document.createElement('option');
                        option.value = element.id;
                        option.text = element.name;
                        lga.add(option)
                    });

                });
        })

        daily_consumption.addEventListener('change', (()=>{
            monthly_consumption.value = daily_consumption.value * 30;
            annual_consumption.value = monthly_consumption.value * 12;
        }))
    </script>
@endsection

resources/views/end-users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Toolbar-->
    <div class="toolbar" id="kt_toolbar">
        <!--begin::Container-->
        <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div data-kt-swapper="true" data-kt-swapper-mode="prepend"
                data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}"
                class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
                <!--begin::Title-->
                <h1 class="d-flex text-dark fw-bolder fs-3 align-items-center my-1">Users</h1>
                <!--end::Title-->
                <!--begin::Separator-->
                <span class="h-20px border-gray-300 border-start mx-4"></span>
                <!--end::Separator-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-muted">
                        <a href="{{ route('app.dashboard') }}" class="text-muted text-hover-primary">Home</a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item">
                        <span class="bullet bg-gray-300 w-5px h-2px"></span>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-muted">User Management</li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item">
                        <span class="bullet bg-gray-300 w-5px h-2px"></span>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-muted"><a href="{{ route('app.users.index') }}" class="text-muted text-hover-primary">Users</a></li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item">
                        <span class="bullet bg-gray-300 w-5px h-2px"></span>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-dark">Update User</li>
                    <!--end::Item-->
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page title-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Toolbar-->
    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container-xxl">
            <!--begin::Card-->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Update User</h3>
                </div>
                <!-- /.card-header -->
                <form action="{{route('app.users.update', $user->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <!-- form start -->
                    <div class="card-body">
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" name="firstname" value="{{old('firstname', isset($user) ? $user->firstname : '')}}" class="form-control" placeholder="Name" id="fullname">
                        </div>
                        <div class="form-group">
                            <label>Last Name</label>
                            <input type="text" name="lastname" value="{{old('lastname', isset($user) ? $user->lastname : '')}}" class="form-control" placeholder="Name" id="fullname">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" name="email" value="{{old('email', isset($user) ? $user->email : '')}}" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label>Phone Number</label>
                            <input type="text" name="phone" value="{{old('phone', isset($user) ? $user->phone : '')}}" class="form-control" placeholder="Phone Number">
                        </div>
                        <div class="form-group">
                            <label>Role</label>
                            <select name="role" class="form-control">
                                <option selected value="{{$user->roles->first()->id}}">{{$user->roles->first()->name}}</option>
                                @foreach ($roles as $role)
                                    <option value='{{ $role->id }}'>{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->
</div>
@endsection

resources/views/end-users/show.blade.php
@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
    <div class="container-xl">
        <!-- Page title -->
        <p></p>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Show - {{ strtoupper($user->FullName()) }}</h3>
                <a href="{{route('app.users.index')}}" class="btn btn-primary ml-auto">Back</a>
            </div>
            <div class="card-body border-bottom py-3">
                <table class="table table-bordered">
                    <tr class="success">
                        <td><strong>Name</strong></th>
                        <td>{{ $user->FullName() }}</td>
                    </tr>
                    <tr class="success">
                        <td><strong>Email</strong></th>
                        <td>{{ $user->email }}</td>
                    </tr>
                    {{-- <tr class="success">
                        <td><strong>Role</strong></th>
                        <td>{{ $user->role }}</td>
                    </tr> --}}
                </table>
            </div>
        </div>
    </div>
@endsection